# Generated by Django 4.2.2 on 2023-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
