# Generated by Django 4.2.2 on 2023-07-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
    ]
