# Generated by Django 4.2.2 on 2023-07-10 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_borrower_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='issue_date',
            field=models.DateTimeField(default=datetime.date(2023, 7, 10)),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(blank=True, upload_to='student_image'),
        ),
    ]
